const mockOrders = [
  {
    id: 1,
    customerName: "Rohidas Lakade",
    email: "rohidaslakade0707@gmail.com",
    phone: "7350764010",
    address: "Ground Floor, Shop no 3, Rajdhani Complex, Pune - 411043",
    cleaningDate: "19 Aug, 2025 at 01:00 PM",
    transactionId: "128-ADV-1755490164",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 4,
    discount: 0,
    shipping: 1,
    paidAmount: 4,
    remainingAmount: 1,
    amount: 5,
    datePurchased: "19 Aug 2025",
    products: [{ name: "Floor Cleaning (1 Sq.ft.)", price: 4, qty: 1 }]
  },
  {
    id: 2,
    customerName: "Dattatray Katore",
    email: "dattakatore012@gmail.com",
    phone: "7038476732",
    address: "Flat 22, Green Valley, Wakad, Pune",
    cleaningDate: "20 Aug, 2025 at 11:30 AM",
    transactionId: "128-ADV-1755490165",
    status: "Pending",
    paymentStatus: "Partial",
    subtotal: 10,
    discount: 2,
    shipping: 0,
    paidAmount: 5,
    remainingAmount: 3,
    amount: 8,
    datePurchased: "20 Aug 2025",
    products: [
      { name: "Sofa Cleaning", price: 5, qty: 1 },
      { name: "Carpet Cleaning", price: 5, qty: 1 }
    ]
  },
  {
    id: 3,
    customerName: "Sandesh Patil",
    email: "patilSandesh@gmail.com",
    phone: "9823012345",
    address: "Baner, Pune",
    cleaningDate: "21 Aug, 2025 at 02:00 PM",
    transactionId: "128-ADV-1755490166",
    status: "Cancelled",
    paymentStatus: "Unpaid",
    subtotal: 7,
    discount: 1,
    shipping: 0,
    paidAmount: 0,
    remainingAmount: 6,
    amount: 6,
    datePurchased: "21 Aug 2025",
    products: [
      { name: "Window Cleaning", price: 3, qty: 2 },
      { name: "Kitchen Cleaning", price: 4, qty: 1 }
    ]
  },
  {
    id: 4,
    customerName: "Anmol Kumbhar",
    email: "anmol.kumbhar@example.com",
    phone: "9867543210",
    address: "Hadapsar, Pune",
    cleaningDate: "22 Aug, 2025 at 10:30 AM",
    transactionId: "128-ADV-1755490167",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 12,
    discount: 2,
    shipping: 1,
    paidAmount: 11,
    remainingAmount: 0,
    amount: 11,
    datePurchased: "22 Aug 2025",
    products: [{ name: "Full House Cleaning", price: 12, qty: 1 }]
  },
  {
    id: 5,
    customerName: "Ajay Jadhav",
    email: "ajay.jadhav@example.com",
    phone: "9811122233",
    address: "Kothrud, Pune",
    cleaningDate: "23 Aug, 2025 at 03:15 PM",
    transactionId: "128-ADV-1755490168",
    status: "Pending",
    paymentStatus: "Partial",
    subtotal: 15,
    discount: 0,
    shipping: 2,
    paidAmount: 10,
    remainingAmount: 7,
    amount: 17,
    datePurchased: "23 Aug 2025",
    products: [
      { name: "Carpet Cleaning", price: 10, qty: 1 },
      { name: "Bathroom Cleaning", price: 5, qty: 1 }
    ]
  },
  {
    id: 6,
    customerName: "Meera Joshi",
    email: "meera.joshi@example.com",
    phone: "9898989898",
    address: "Viman Nagar, Pune",
    cleaningDate: "24 Aug, 2025 at 12:00 PM",
    transactionId: "128-ADV-1755490169",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 20,
    discount: 5,
    shipping: 0,
    paidAmount: 15,
    remainingAmount: 0,
    amount: 15,
    datePurchased: "24 Aug 2025",
    products: [{ name: "Deep Cleaning Package", price: 20, qty: 1 }]
  },
  {
    id: 7,
    customerName: "RDS LKD",
    email: "rdslkd5555@example.com",
    phone: "7350764010",
    address: "Viman Nagar, Pune",
    cleaningDate: "28 Aug, 2025 at 12:00 PM",
    transactionId: "128-ADV-1755490170",
    status: "Cancelled",
    paymentStatus: "Paid",
    subtotal: 20,
    discount: 5,
    shipping: 0,
    paidAmount: 15,
    remainingAmount: 0,
    amount: 15,
    datePurchased: "28 Aug 2025",
    products: [{ name: "Deep Cleaning Package", price: 20, qty: 1 }]
  },
  {
    id: 8,
    customerName: "Ravi Bishnoi",
    email: "ravi@example.com",
    phone: "8564752536",
    address: "Aundh, Pune",
    cleaningDate: "14 Jun, 2025 at 01:00 PM",
    transactionId: "128-ADV-1755490171",
    status: "Pending",
    paymentStatus: "Paid",
    subtotal: 18,
    discount: 2,
    shipping: 1,
    paidAmount: 17,
    remainingAmount: 0,
    amount: 19,
    datePurchased: "14 Jun 2025",
    products: [{ name: "Deep Cleaning Package", price: 18, qty: 1 }]
  },
  {
    id: 9,
    customerName: "Supriya Deshmukh",
    email: "supriyadesh@example.com",
    phone: "9548756892",
    address: "Shivaji Nagar, Pune",
    cleaningDate: "24 Aug, 2025 at 12:00 PM",
    transactionId: "128-ADV-1755490172",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 25,
    discount: 5,
    shipping: 0,
    paidAmount: 20,
    remainingAmount: 0,
    amount: 20,
    datePurchased: "24 Aug 2025",
    products: [{ name: "Full Deep Cleaning", price: 25, qty: 1 }]
  },
  {
    id: 10,
    customerName: "Suryvanshi RK",
    email: "rk@example.com",
    phone: "7389658798",
    address: "Camp, Pune",
    cleaningDate: "25 Aug, 2025 at 03:00 PM",
    transactionId: "128-ADV-1755490173",
    status: "Confirmed",
    paymentStatus: "Unpaid",
    subtotal: 15,
    discount: 0,
    shipping: 0,
    paidAmount: 0,
    remainingAmount: 15,
    amount: 15,
    datePurchased: "25 Aug 2025",
    products: [{ name: "Carpet Shampooing", price: 15, qty: 1 }]
  },
  {
    id: 11,
    customerName: "Kiran More",
    email: "kiran.more@example.com",
    phone: "9876543100",
    address: "Nigdi, Pune",
    cleaningDate: "26 Aug, 2025 at 11:00 AM",
    transactionId: "128-ADV-1755490174",
    status: "Pending",
    paymentStatus: "Partial",
    subtotal: 8,
    discount: 1,
    shipping: 0,
    paidAmount: 4,
    remainingAmount: 3,
    amount: 7,
    datePurchased: "26 Aug 2025",
    products: [{ name: "Kitchen Cleaning", price: 8, qty: 1 }]
  },
  {
    id: 12,
    customerName: "Pooja Shinde",
    email: "pooja.shinde@example.com",
    phone: "9823456789",
    address: "Bhosari, Pune",
    cleaningDate: "27 Aug, 2025 at 01:30 PM",
    transactionId: "128-ADV-1755490175",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 12,
    discount: 2,
    shipping: 1,
    paidAmount: 11,
    remainingAmount: 0,
    amount: 11,
    datePurchased: "27 Aug 2025",
    products: [{ name: "Window Cleaning", price: 6, qty: 2 }]
  },
  {
    id: 13,
    customerName: "Nilesh Kadam",
    email: "nilesh.kadam@example.com",
    phone: "9812345678",
    address: "Kharadi, Pune",
    cleaningDate: "28 Aug, 2025 at 09:45 AM",
    transactionId: "128-ADV-1755490176",
    status: "Cancelled",
    paymentStatus: "Unpaid",
    subtotal: 20,
    discount: 0,
    shipping: 0,
    paidAmount: 0,
    remainingAmount: 20,
    amount: 20,
    datePurchased: "28 Aug 2025",
    products: [{ name: "Bathroom Cleaning", price: 10, qty: 2 }]
  },
  {
    id: 14,
    customerName: "Ritika Sharma",
    email: "ritika.sharma@example.com",
    phone: "9723456789",
    address: "Sinhagad Road, Pune",
    cleaningDate: "29 Aug, 2025 at 10:15 AM",
    transactionId: "128-ADV-1755490177",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 18,
    discount: 3,
    shipping: 1,
    paidAmount: 16,
    remainingAmount: 0,
    amount: 16,
    datePurchased: "29 Aug 2025",
    products: [{ name: "Sofa Cleaning", price: 18, qty: 1 }]
  },
  {
    id: 15,
    customerName: "Amit Pawar",
    email: "amit.pawar@example.com",
    phone: "9623456789",
    address: "Katraj, Pune",
    cleaningDate: "30 Aug, 2025 at 02:00 PM",
    transactionId: "128-ADV-1755490178",
    status: "Pending",
    paymentStatus: "Partial",
    subtotal: 14,
    discount: 2,
    shipping: 0,
    paidAmount: 7,
    remainingAmount: 5,
    amount: 12,
    datePurchased: "30 Aug 2025",
    products: [{ name: "Carpet Cleaning", price: 14, qty: 1 }]
  },

  // ---- Remaining 16 to 30 orders ----
  {
    id: 16,
    customerName: "Snehal Patil",
    email: "snehal.patil@example.com",
    phone: "9898123456",
    address: "Karve Nagar, Pune",
    cleaningDate: "31 Aug, 2025 at 11:00 AM",
    transactionId: "128-ADV-1755490179",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 22,
    discount: 2,
    shipping: 0,
    paidAmount: 20,
    remainingAmount: 0,
    amount: 20,
    datePurchased: "31 Aug 2025",
    products: [{ name: "Full House Cleaning", price: 22, qty: 1 }]
  },
  {
    id: 17,
    customerName: "Rajesh Nair",
    email: "rajesh.nair@example.com",
    phone: "9819988776",
    address: "Vishrantwadi, Pune",
    cleaningDate: "01 Sep, 2025 at 01:30 PM",
    transactionId: "128-ADV-1755490180",
    status: "Cancelled",
    paymentStatus: "Unpaid",
    subtotal: 16,
    discount: 0,
    shipping: 0,
    paidAmount: 0,
    remainingAmount: 16,
    amount: 16,
    datePurchased: "01 Sep 2025",
    products: [{ name: "Bathroom Cleaning", price: 8, qty: 2 }]
  },
  {
    id: 18,
    customerName: "Pratiksha Gaikwad",
    email: "pratiksha.gaikwad@example.com",
    phone: "9822113344",
    address: "Hinjewadi, Pune",
    cleaningDate: "02 Sep, 2025 at 09:30 AM",
    transactionId: "128-ADV-1755490181",
    status: "Pending",
    paymentStatus: "Partial",
    subtotal: 18,
    discount: 2,
    shipping: 1,
    paidAmount: 9,
    remainingAmount: 8,
    amount: 17,
    datePurchased: "02 Sep 2025",
    products: [{ name: "Kitchen Cleaning", price: 18, qty: 1 }]
  },
  {
    id: 19,
    customerName: "Deepak Shukla",
    email: "deepak.shukla@example.com",
    phone: "9933445566",
    address: "Magarpatta, Pune",
    cleaningDate: "03 Sep, 2025 at 03:00 PM",
    transactionId: "128-ADV-1755490182",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 12,
    discount: 2,
    shipping: 1,
    paidAmount: 11,
    remainingAmount: 0,
    amount: 11,
    datePurchased: "03 Sep 2025",
    products: [{ name: "Window Cleaning", price: 6, qty: 2 }]
  },
  {
    id: 20,
    customerName: "Anjali Verma",
    email: "anjali.verma@example.com",
    phone: "9988776655",
    address: "Koregaon Park, Pune",
    cleaningDate: "04 Sep, 2025 at 12:00 PM",
    transactionId: "128-ADV-1755490183",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 30,
    discount: 5,
    shipping: 0,
    paidAmount: 25,
    remainingAmount: 0,
    amount: 25,
    datePurchased: "04 Sep 2025",
    products: [{ name: "Deep Cleaning Package", price: 30, qty: 1 }]
  },
  {
    id: 21,
    customerName: "Manoj Kale",
    email: "manoj.kale@example.com",
    phone: "9722334455",
    address: "Hadapsar, Pune",
    cleaningDate: "05 Sep, 2025 at 11:15 AM",
    transactionId: "128-ADV-1755490184",
    status: "Pending",
    paymentStatus: "Partial",
    subtotal: 20,
    discount: 3,
    shipping: 2,
    paidAmount: 10,
    remainingAmount: 9,
    amount: 19,
    datePurchased: "05 Sep 2025",
    products: [{ name: "Sofa Cleaning", price: 20, qty: 1 }]
  },
  {
    id: 22,
    customerName: "Priya Singh",
    email: "priya.singh@example.com",
    phone: "9844556677",
    address: "Pimple Saudagar, Pune",
    cleaningDate: "06 Sep, 2025 at 10:00 AM",
    transactionId: "128-ADV-1755490185",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 15,
    discount: 0,
    shipping: 0,
    paidAmount: 15,
    remainingAmount: 0,
    amount: 15,
    datePurchased: "06 Sep 2025",
    products: [{ name: "Bathroom Cleaning", price: 15, qty: 1 }]
  },
  {
    id: 23,
    customerName: "Aakash Pawar",
    email: "aakash.pawar@example.com",
    phone: "9822123456",
    address: "Wakad, Pune",
    cleaningDate: "07 Sep, 2025 at 02:00 PM",
    transactionId: "128-ADV-1755490186",
    status: "Cancelled",
    paymentStatus: "Unpaid",
    subtotal: 10,
    discount: 0,
    shipping: 0,
    paidAmount: 0,
    remainingAmount: 10,
    amount: 10,
    datePurchased: "07 Sep 2025",
    products: [{ name: "Kitchen Cleaning", price: 10, qty: 1 }]
  },
  {
    id: 24,
    customerName: "Seema Rane",
    email: "seema.rane@example.com",
    phone: "9766443322",
    address: "Kharadi, Pune",
    cleaningDate: "08 Sep, 2025 at 09:00 AM",
    transactionId: "128-ADV-1755490187",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 28,
    discount: 3,
    shipping: 2,
    paidAmount: 27,
    remainingAmount: 0,
    amount: 27,
    datePurchased: "08 Sep 2025",
    products: [{ name: "Full Deep Cleaning", price: 28, qty: 1 }]
  },
  {
    id: 25,
    customerName: "Rohan Kulkarni",
    email: "rohan.kulkarni@example.com",
    phone: "9855332211",
    address: "Baner, Pune",
    cleaningDate: "09 Sep, 2025 at 04:00 PM",
    transactionId: "128-ADV-1755490188",
    status: "Pending",
    paymentStatus: "Partial",
    subtotal: 14,
    discount: 2,
    shipping: 1,
    paidAmount: 7,
    remainingAmount: 6,
    amount: 13,
    datePurchased: "09 Sep 2025",
    products: [{ name: "Sofa Cleaning", price: 14, qty: 1 }]
  },
  {
    id: 26,
    customerName: "Sunita Yadav",
    email: "sunita.yadav@example.com",
    phone: "9888776655",
    address: "Camp, Pune",
    cleaningDate: "10 Sep, 2025 at 01:30 PM",
    transactionId: "128-ADV-1755490189",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 19,
    discount: 2,
    shipping: 0,
    paidAmount: 17,
    remainingAmount: 0,
    amount: 17,
    datePurchased: "10 Sep 2025",
    products: [{ name: "Window Cleaning", price: 19, qty: 1 }]
  },
  {
    id: 27,
    customerName: "Ankita Desai",
    email: "ankita.desai@example.com",
    phone: "9977665544",
    address: "Nigdi, Pune",
    cleaningDate: "11 Sep, 2025 at 03:15 PM",
    transactionId: "128-ADV-1755490190",
    status: "Cancelled",
    paymentStatus: "Unpaid",
    subtotal: 22,
    discount: 0,
    shipping: 0,
    paidAmount: 0,
    remainingAmount: 22,
    amount: 22,
    datePurchased: "11 Sep 2025",
    products: [{ name: "Bathroom Cleaning", price: 11, qty: 2 }]
  },
  {
    id: 28,
    customerName: "Vikas Sharma",
    email: "vikas.sharma@example.com",
    phone: "9833445566",
    address: "Sinhagad Road, Pune",
    cleaningDate: "12 Sep, 2025 at 10:45 AM",
    transactionId: "128-ADV-1755490191",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 25,
    discount: 5,
    shipping: 1,
    paidAmount: 21,
    remainingAmount: 0,
    amount: 21,
    datePurchased: "12 Sep 2025",
    products: [{ name: "Full House Cleaning", price: 25, qty: 1 }]
  },
  {
    id: 29,
    customerName: "Komal Bhosale",
    email: "komal.bhosale@example.com",
    phone: "9811445566",
    address: "Viman Nagar, Pune",
    cleaningDate: "13 Sep, 2025 at 09:30 AM",
    transactionId: "128-ADV-1755490192",
    status: "Pending",
    paymentStatus: "Partial",
    subtotal: 13,
    discount: 1,
    shipping: 0,
    paidAmount: 6,
    remainingAmount: 6,
    amount: 12,
    datePurchased: "13 Sep 2025",
    products: [{ name: "Kitchen Cleaning", price: 13, qty: 1 }]
  },
  {
    id: 30,
    customerName: "Nikhil Chavan",
    email: "nikhil.chavan@example.com",
    phone: "9822556677",
    address: "Katraj, Pune",
    cleaningDate: "14 Sep, 2025 at 02:30 PM",
    transactionId: "128-ADV-1755490193",
    status: "Confirmed",
    paymentStatus: "Paid",
    subtotal: 20,
    discount: 3,
    shipping: 1,
    paidAmount: 18,
    remainingAmount: 0,
    amount: 18,
    datePurchased: "14 Sep 2025",
    products: [{ name: "Sofa Cleaning", price: 20, qty: 1 }]
  }
];

export default mockOrders;